apiVersion: v1
values:
  images:
    componentOperator: cloudogu/k8s-component-operator:1.12.0
    defaultConfig: cloudogu/ecosystem-core-default-config:1.0.0
    kubectl: docker.io/alpine/kubectl:1.34.0
patches:
  values.yaml:
    k8s-component-operator:
      manager:
        image:
          registry: "{{ registryFrom .images.componentOperator }}"
          repository: "{{ repositoryFrom .images.componentOperator }}"
          tag: "{{ tagFrom .images.componentOperator }}"
    cleanup:
      image:
        registry: "{{ registryFrom .images.kubectl }}"
        repository: "{{ repositoryFrom .images.kubectl }}"
        tag: "{{ tagFrom .images.kubectl }}"
    defaultConfig:
      image:
        registry: "{{ registryFrom .images.defaultConfig }}"
        repository: "{{ repositoryFrom .images.defaultConfig }}"
        tag: "{{ tagFrom .images.defaultConfig }}"
