# Default values for ecosystem-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
skipPreconditionValidation: true
loadbalancer-annotations: {}
k8s-component-operator:
  manager:
    image:
      registry: docker.io
      repository: cloudogu/k8s-component-operator
      tag: 1.12.0
    env:
      logLevel: info
    resourceLimits:
      memory: 105M
    resourceRequests:
      cpu: 15m
      memory: 105M
    networkPolicies:
      enabled: true
components:
  k8s-dogu-operator-crd:
    version: 2.10.0
  k8s-dogu-operator:
    version: 3.15.0
  k8s-service-discovery:
    version: 4.0.0
  k8s-blueprint-operator-crd:
    version: 3.1.0
  k8s-blueprint-operator:
    version: 3.0.2
  k8s-ces-gateway:
    version: 2.0.0
  k8s-ces-assets:
    version: 1.0.4
  k8s-ces-control:
    version: 1.8.0
  k8s-debug-mode-operator-crd:
    version: 1.0.0
  k8s-debug-mode-operator:
    version: 1.0.0
backup:
  enabled: true
  # The backup stack requires the snapshot api and snapshot controller to be installed. It is not party of the ecosystem and should be seen as an infrastructure component like the storage provisioner.
  # In cloud environments like GKE, the snapshot controller is installed by default. In other environments, it needs to be installed manually.
  # For manual installation (like in k3s environments) see https://github.com/kubernetes-csi/external-snapshotter.
  components:
    k8s-backup-operator-crd:
      version: 1.7.0
    k8s-backup-operator:
      version: 2.0.0
    k8s-velero:
      version: 10.0.1-5
monitoring:
  enabled: true
  components:
    k8s-prometheus:
      version: 75.3.5-3
    k8s-minio:
      version: 2025.6.13-2
    k8s-loki:
      version: 3.3.2-6
    k8s-promtail:
      version: 2.9.1-9
    k8s-alloy:
      version: 1.1.2-1
    k8s-support-archive-operator-crd:
      version: 1.0.0
    k8s-support-archive-operator:
      version: 1.0.1
cleanup:
  timeoutSeconds: 900
  image:
    registry: docker.io
    repository: alpine/kubectl
    tag: 1.34.0
defaultConfig:
  image:
    registry: docker.io
    repository: cloudogu/ecosystem-core-default-config
    tag: 1.2.0
  imagePullPolicy: IfNotPresent
  env:
    logLevel: info
    waitTimeoutMinutes: 5
